import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { parseCommand } from '../utils/nlp';

export const useStore = create(
  persist(
    (set, get) => ({
      user: { name: "Commander" },
      schedule: [],
      status: "idle",
      
      // --- NEW: ANALYSIS MODE STATE ---
      isAnalysisMode: false,
      currentQuestionIndex: 0,
      dailyAnswers: [],
      questions: [
        "What is the single most critical objective for today?",
        "On a scale of 1-10, what is your current energy level?",
        "Are there any lingering conflicts from yesterday?",
        "What habit do you want to strictly enforce today?",
        "Who do you need to contact to unblock your progress?",
        // ... In a real backend, these would be generated by AI. We start with 5 for testing.
      ],

      // --- ACTIONS ---
      setAnalysisMode: (active) => set({ isAnalysisMode: active }),
      
      submitAnswer: (answer) => set((state) => {
        const newAnswers = [...state.dailyAnswers, { 
            question: state.questions[state.currentQuestionIndex], 
            answer, 
            timestamp: new Date().toISOString() 
        }];
        
        // Move to next question or finish
        const nextIndex = state.currentQuestionIndex + 1;
        const isFinished = nextIndex >= state.questions.length;

        return {
            dailyAnswers: newAnswers,
            currentQuestionIndex: isFinished ? 0 : nextIndex,
            isAnalysisMode: !isFinished, // Close mode if finished
            // If finished, we could trigger a "Summary" task here
             schedule: isFinished ? [...state.schedule, {
                id: Date.now(),
                text: "Review Daily Analysis Data",
                type: "system",
                time: "NOW",
                dateObj: new Date()
            }] : state.schedule
        };
      }),

      addTask: (input) => set((state) => {
        const data = parseCommand(input);
        const newItem = { 
            id: Date.now(), 
            text: data.text, 
            type: data.type,
            time: data.time || "TBD",
            dateObj: data.dateObj 
        };
        const newSchedule = [...state.schedule, newItem].sort((a, b) => {
            if (!a.dateObj && !b.dateObj) return 0;
            if (!a.dateObj) return 1;
            if (!b.dateObj) return -1;
            return new Date(a.dateObj) - new Date(b.dateObj);
        });
        return { schedule: newSchedule };
      }),

      removeTask: (id) => set((state) => ({
        schedule: state.schedule.filter(t => t.id !== id)
      })),

      setStatus: (status) => set({ status })
    }),
    {
      name: 'jarvis-storage', 
    }
  )
);
